name: Build native library of imgui-java for Linux

on:
  push:
    tags:
      - "mtt-imgui-java-natives-all-*"
      - "mtt-imgui-java-natives-linux-*"

permissions:
  contents: write

jobs:
  build:
    name: Build native library of imgui-java for Linux
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: Misc/imgui-java
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install gcc and g++
        run: |
          sudo apt update
          sudo apt install gcc g++
      - name: Build lib-imgui-java
        run: ./gradlew imgui-binding:generateLibs -Denvs=linux -Dlocal
      - name: Publish build artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: Misc/imgui-java/imgui-binding/build/libsNative/linux64/libimgui-java64.so
