name: Build native library of libmttslangc for macOS arm64

on:
  push:
    tags:
      - "mttslangc-natives-all-*"
      - "mttslangc-natives-macosarm64-*"

jobs:
  build:
    name: Build native library of libmttslangc for macOS arm64
    permissions:
      contents: write
    runs-on: macos-15
    defaults:
      run:
        working-directory: mechtatel-natives/natives/lib-mttslangc
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Init and update submodules
        run: git submodule update --init
      - name: Download Slang release
        run: |
          mkdir Download && cd Download
          wget https://github.com/shader-slang/slang/releases/download/v2025.17/slang-2025.17-macos-aarch64.tar.gz
          tar -xf slang-2025.17-macos-aarch64.tar.gz
      - name: Copy libslang.dylib to lib directory
        run: |
          mkdir lib
          cp ./Download/lib/libslang.dylib ./lib/
      - name: Build libmttslangc
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      - name: Publish build artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: mechtatel-natives/natives/lib-mttslangc/build/libmttslangc.dylib
